---
- name: Create 'admin' group
  group:
    name: admin

- name: Allow 'admin' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%admin'
    line: '%admin ALL=(ALL) NOPASSWD: ALL'

- name: Create users
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: "{{ item.groups }}"
  with_items: "{{ users }}"

- name: Set up authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: '{{ item.key }}'
  with_items: "{{ users }}"
